language: php

sudo: false

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm-3.18
  - hhvm-nightly
  - nightly

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: nightly

addons:
  apt:
    packages:
    - devscripts
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make

before_install:
  - composer self-update
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN} && composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;

before_script:
  - composer install --no-interaction
  - if [ "$TRAVIS_PHP_VERSION" = "7.2" ]; then composer require php-coveralls/php-coveralls --no-interaction; fi

script:
  - make qa_all
  - make report

after_failure:
  - cat ./target/logs/junit.xml
  - cat ./target/report/phpcpd.txt

after_success:
  - cat ./target/report/phploc.txt
  - cat ./target/report/phpcompatinfo.txt
  - "echo 'coverage_clover: target/coverage/coverage.xml' >> .coveralls.yml"
  - "echo 'json_path: target/coverage/coveralls-upload.json' >> .coveralls.yml"
  - if [ "$TRAVIS_PHP_VERSION" = "7.2" ]; then php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v; fi;
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PHP_VERSION" = "7.2" ] && [ -n "$BT_APIUSER" ]; then make bintray APIUSER=${BT_APIUSER} APIKEY=${BT_APIKEY}; fi;
